/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Aug 17 2023
 * Processor: 8086
 * Compiler:  Digital Mars C
 *
 * Before starting simulation set Internal Memory Size 
 * in the 8086 model properties to 0x10000
 */
 
#define IO0 	0x0000
#define IO1 	0x0200
#define IO2 	0x0400
#define IO3 	0x0600
#define IO4 	0x0800
#define IO5 	0x0A00
#define IO6 	0x0C00
#define IO7 	0x0E00
#define IO8 	0x1000
#define IO9 	0x1200
#define IO10 	0x1400
#define IO11 	0x1600
#define IO12 	0x1800
#define IO13 	0x1A00
#define IO14 	0x1C00
#define IO15 	0x1E00

unsigned char TABELA_7_SEG[] = {
    0b00111111, // 0
    0b00000110, // 1
    0b01011011, // 2
    0b01001111, // 3
    0b01100110, // 4
    0b01101101, // 5
    0b01111101, // 6
    0b00000111, // 7
    0b01111111, // 8
    0b01101111, // 9
    0b01110111, // A
    0b01111100, // B
    0b00111001, // C
    0b01011110, // D
    0b01111001, // F
};

void main(void) {
    while (1) {
        for (int i = 0; i < sizeof(TABELA_7_SEG); i++) {
            unsigned char display_data = TABELA_7_SEG[i];
            
            asm {
                mov dx, IO1
                in  al, dx
                and al, 0b00001111
                mov bl, al
                mov bh, 0
                mov al, display_data
                mov dx, IO0
                out dx, al
            }
            
            for (volatile int delay = 0; delay < 30000; delay++) {
            }
        }
    }
}
 